#### Numpy
    pip install numpy

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a                                #4x1 배열, 행렬

array([1, 2, 3, 4])

In [4]:
type(a)                 #넘파이는 ndarray 객체이다.

numpy.ndarray

In [5]:
a.dtype

dtype('int32')

In [17]:
a = np.array([1,2,3,4])
a     

array([1, 2, 3, 4])

In [15]:
a1 = np.array([[1.0,2.1,3,4]])
a1.dtype     

dtype('float64')

In [7]:
a

array([1. , 2.1, 3. , 4. ])

2차원

In [11]:
a2 = np.array([[1,2,3.0,4.0],
            [0.1,2.0,9.0,10.0]])         # 2x4 배열
a2     

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 0.1,  2. ,  9. , 10. ]])

속성

In [13]:
a.dtype, a2.dtype

(dtype('float64'), dtype('float64'))

In [18]:
a.shape, a1.shape, a2.shape       

((4,), (1, 4), (2, 4))

In [19]:
a.ndim, a1.ndim, a2.ndim

(1, 2, 2)

np.arange()

In [21]:
arr1 = np.arange(30)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
arr1.ndim             #1차원

1

In [27]:
arr1 = np.arange(30).reshape(5,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [29]:
arr1.ndim             #2차원

2

In [31]:
arr1 = arr1.reshape(30,)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
arr1.ndim          #다시 1차원

1

In [33]:
arr2 = np.ndarray(shape=(5,6), dtype='float64')
arr2

array([[1.10585155e-311, 9.58487353e-322, 0.00000000e+000,
        0.00000000e+000, 2.56929895e+151, 1.16097020e-028],
       [6.37112413e-067, 9.71520605e-067, 2.73886134e-057,
        5.01163173e+217, 8.37170074e-144, 5.24147676e+174],
       [1.14195556e-071, 7.11939819e-091, 4.12124376e-061,
        5.01163107e+217, 5.49419094e-143, 9.80058441e+252],
       [7.50189709e+247, 1.35617292e+248, 3.98374080e+175,
        5.51160337e+169, 2.31982886e-052, 8.23009166e-071],
       [6.45085936e-067, 5.04621361e+180, 8.37170571e-144,
        9.30350598e+199, 5.60230216e-067, 5.37954348e+173]])

In [34]:
arr2.shape, arr2.ndim

((5, 6), 2)

영행렬, 일행렬

In [35]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [39]:
m = np.zeros((5,6))
m.ndim

2

In [40]:
m2 = np.ones((5,6))
m2.ndim

2

np.random.radn()

In [42]:
arr = np.random.randn(2,3)
arr

array([[ 0.62153468, -2.26323158,  0.16332712],
       [-1.18670703,  0.51112596, -1.45040007]])

In [46]:
arr1  = np.array([[1,2,3], [4,5,6]], dtype=np.uint64)
arr1.dtype, arr1.shape

(dtype('uint64'), (2, 3))

In [45]:
arr1.dtype

dtype('float64')

In [ ]:
arr1  = np.array([[1,2,3], [4,5,6]], dtype='float64')
arr1

In [47]:
arr1 = arr1.astype(np.float16)
arr1.dtype

dtype('float16')

### Fancy indexing
    1)논리 조건
    2)필터
    3)ndarray 등에 일치하는 인덱스 요소

In [48]:
# index
arr = np.array([1,2,3,4,5,6])
idx = np.array([False,True, True, False, False, True])

In [49]:
arr[idx]

array([2, 3, 6])

In [51]:
arr % 2

array([1, 0, 1, 0, 1, 0], dtype=int32)

In [52]:
arr % 2 == 0

array([False,  True, False,  True, False,  True])

In [54]:
arr[ arr % 2 == 0]        #fancy indexing

array([2, 4, 6])

#### Inf, NaN
    무한대
    Not a Number

In [57]:
np.array([0,1,-1,0])/ np.array([1,0,0,0])

C:\Users\BIT_R39\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\BIT_R39\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [58]:
np.inf

inf